MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN_ONLY: True
  EMBED_MASK_ON: True
  MASK_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  EMBED_MASK:
    EMBED_DIM: 8
    SAMPLE_IN_MASK: True
    FIX_MARGIN: False
    BOX_PADDING: 0.1
    PRIOR_MARGIN: 2.0
    LOSS_MASK_ALPHA: 0.5
    MASK_SCALE_FACTOR: 2
    MASK_NUM_CONVS: 4
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  # TEST: ("coco_2017_test_dev",)
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 16
  WARMUP_METHOD: "constant"
